title: GDP - Generátor D&D postav
baseURL: https://condescending-meninsky-2ba4c5.netlify.com/
languageCode: cs-cz
publishDir: public
googleAnalytics: UA-139401208-1

menu:
  main:
    - name: Rozcestník
      url: /
      weight: 10
    - name: Archiv
      identifier: post
      url: /post/
      weight: 20

params:
  description: Stránka o hře Dungeons & Dragons a o všem s ní spojené.
  authors: Studenti NaMI
