title: GDP - Generátor D&D postav
baseURL: https://condescending-meninsky-2ba4c5.netlify.com/
languageCode: cs-cz
publishDir: public
googleAnalytics: UA-139401208-1

menu:
  main:
    - name: Homepage
      url: /
      weight: 10
    - name: Archive
      identifier: post
      url: /post/
      weight: 20

params:
  description: Description of my new site.
  authors: Authors

